name: Release
on:
    workflow_dispatch:
    push:
        tags: ['v*']

permissions:
    contents: write
    pull-requests: write

jobs:
    release:
        uses: shiv-source/golden-path/.github/workflows/release-github.yaml@v1
        with:
            tag-prefix: v
            generate-release-notes: true
